# Generated by Django 3.2.25 on 2024-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0004_switch_to_django_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='incumbent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='offices',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='election',
            name='enabled',
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='last_import_successful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='representative',
            name='offices',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='representativeset',
            name='enabled',
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='representativeset',
            name='last_import_successful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
