name: Lint
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install --upgrade check-manifest flake8 isort
      - run: flake8 .
      - run: isort .
      - run: check-manifest
